### ISSUE TITLE
Error on download 

### ISSUE THREAD

**Issue by MGodfrey50** [Azure/review-checklists#198]
Error when downloading the file

"Excel cannot open the file 'review_****.xlsm' because the file format or file extension is not valid.   Verify that the file has not been corrupted and that the file extension matches the format of the file."

Multiple people, multiple locations.

**Comment by sdolgin** [comment]
@MGodfrey50 - as a workaround there are now "static" / non-macro xlsx files being generated under the [/spreadsheet](https://github.com/Azure/review-checklists/tree/main/spreadsheet) path. Hope that helps!

**Comment by erjosito** [comment]
The problem seems to appear when you download the spreadsheet to onedrive, since Defender is blocking the opening of xlsm exceptions. One workaround would be downloading the spreadsheet to your C:\ drive.

I am testing with adding an exclusion to Azure Defender for the onedrive folder, but it doesnt seem to work.
