### ISSUE TITLE
add other technologies in checklist_graph.sh

### ISSUE THREAD

**Issue by khatrisalah** [Azure/review-checklists#311]
Hi,

I am trying to use checklist_graph.sh to get other technologies mentioned in the https://github.com/Azure/review-checklists/tree/main/checklists, in the script as of now only [lz|aks|avd] is mentioned others are not there.
I have tried to copy the script locally and tried to add other technologies in script"$script_name [--technology=lz|aks|avd|security|acr_seucrity|apim|appsvc_security|blob_storage_security|multitenancy|sap|sqldb_security], i tried to run this script in the cloud shell after changing the script but got an error  "bash: ./checklist_graph2.sh: /usr/bin/zsh^M: bad interpreter: No such file or directory"

can you please update the sh file by adding more technologies.

Thank you

**Comment by cheahengsoon** [comment]
@MGodfrey50 as mention the **security** technologies was GA , but the checklist_graph2.sh did not updated.

**Comment by erjosito** [comment]
Hey sorry for the delay picking this one up. I have changed the `checklist_graph.sh` script so that the technology (checklist) is now free text, and added the option --list-technologies to find out which checklists are available.

Note that the checklist itself needs to have those graph queries documented...
