### ISSUE TITLE
autoscaler query wrong in aks_checklist.en_workbook.json

### ISSUE THREAD

**Issue by jaywithersbrewin** [Azure/review-checklists#368]
Current (wrong) query:

"where type=='microsoft.containerservice/managedclusters' | extend compliant = (isnotnull(properties.austoscalerProfile)) | distinct id,compliant"

Proposed (new) query:

"where type=='microsoft.containerservice/managedclusters' | extend compliant = (isnotnull(properties.autoScalerProfile)) | distinct id,compliant"

**Comment by erjosito** [comment]
Thanks @jaywithersbrewin ! The checklist queries and the workbook should be updated now :-)  For next time, if you want, feel free to send a PR to the origin of the workbook file, for AKS it would be https://github.com/Azure/review-checklists/blob/main/checklists/aks_checklist.en.json. Otherwise issues like these one are fine too :-)
