### ISSUE TITLE
ALZ checklist: Defender4Cloud standard - Severity -> High

### ISSUE THREAD

**Issue by erjosito** [Azure/review-checklists#474]
Item with GUID `09945bda-4333-44f2-9911-634182ba5275` should probably be priority High. As reported by Suzy Esteves, "in AMM the SOW has DfC as mandatory".

@brsteph could the ALZ team look into this? Thanks!

**Comment by brsteph** [comment]
@erjosito - 

There is more clarity needed for this recommendation over all.  Defender for Cloud Standard isn't a meaningful designation with the new plan approach.

We should have recommendation for the options defined in [D4C Pricing](https://azure.microsoft.com/en-us/pricing/details/defender-for-cloud/?v=17.23h).

For example, are we saying that we want Defender Cloud Security Posture Management enabled on each resource, or that all Servers are on Plan 2, or something else.

This might be its own category with multiple recommendations, some high and some medium.

@BeckyHope19 has volunteered to look into this more and create a pull request with changes to reflect that.  We should check that against the upcoming PRs already in flight as well, because they contain the same recommendation.

**Comment by BeckyHope19** [comment]
The recommendation will be replaced with the following:

Enable Defender Cloud Security Posture Management for all subscriptions - High
(https://learn.microsoft.com/en-us/azure/defender-for-cloud/concept-cloud-security-posture-management)

Enable a Defender Cloud Workload Protection Plan for Servers on all subscriptions - High
(https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-defender-for-servers-select-plan)

Enable Defender Cloud Workload Protection Plans for Azure Resources on all subscriptions - High
(https://www.microsoft.com/en-gb/security/business/solutions/cloud-workload-protection)

Enable Endpoint Protection on IaaS Servers - High
(https://learn.microsoft.com/en-us/mem/configmgr/protect/deploy-use/endpoint-protection)

I will be making the pull request today.

**Comment by BeckyHope19** [comment]
PR requested was raised, it is just waiting to be approved.

**Comment by brsteph** [comment]
PR #481 was merged, so this should be completed!
